from A4_Base import *
from A4_ToDo import *

#NOTE: DO NOT EDIT THIS FILE
#NOTE: ONLY USE THIS FILE TO TEST IF YOUR IMPLEMENTATION IS CORRECT
# The test cases will run individual instances of the problem and print "PASSED" if your implementation is correct.

def test_astar_search():
    romania_problem = AStarGraph('Arad', 'Bucharest', romania_map)
    assert astar_search(romania_problem,romania_problem.h).solution() == ['Sibiu', 'Rimnicu', 'Pitesti', 'Bucharest']


    romania_problem = AStarGraph('Oradea', 'Eforie', romania_map)
    #print(astar_search(romania_problem).solution())
    assert astar_search(romania_problem).solution() == ['Sibiu', 'Rimnicu', 'Pitesti', 'Bucharest', 'Urziceni', 'Hirsova', 'Eforie']